### ISSUE TITLE
Seed function is invalid exception

### ISSUE THREAD

**Issue by AHMED-salah00** [ai4co/LLM-as-HH#2]
Hello ReEvo team!

I've been trying to use ziphuAi instead of Gpt4 to run the prompts. I've provided the api key for ziphuAi, and I've done some changes in the config.yaml to enable that.

```
# LLM parameters
model: GLM-4  # LLM model (other options include gpt-4-turbo-preview, GLM-3-Turbo, GLM-4)
temperature: 1  # temperature for chat completion
suffix: GLM  # suffix for generated files (indicates LLM model)
```
but when I run the code an exception happens due to seed function. Can you please help with that?

Here is the full error:
```
python main.py problem=tsp_constructive algorithm=reevo
[2024-04-08 13:05:18,818][root][INFO] - Workspace: C:\Users\kjkj0\LLM-as-HH\outputs\main\2024-04-08_13-05-18
[2024-04-08 13:05:18,819][root][INFO] - Project Root: C:\Users\kjkj0\LLM-as-HH
[2024-04-08 13:05:18,819][root][INFO] - Using LLM: GLM-4
[2024-04-08 13:05:18,819][root][INFO] - Using Algorithm: reevo
[2024-04-08 13:05:19,378][root][INFO] - Problem: tsp_constructive
[2024-04-08 13:05:19,378][root][INFO] - Problem description: Solving Traveling Salesman Problem (TSP) with constructive heuristics. TSP requires finding the shortest path that visits all given nodes and returns to the starting node.
[2024-04-08 13:05:19,378][root][INFO] - Function name: select_next_node
[2024-04-08 13:05:19,379][root][INFO] - Evaluating seed function...
[2024-04-08 13:05:19,389][root][INFO] - Seed function code:
import numpy as np
def select_next_node_v2(current_node: int, destination_node: int, unvisited_nodes: set, distance_matrix: np.ndarray) -> int:
    """Select the next node to visit from the unvisited nodes."""
    threshold = 0.7
    c1, c2, c3, c4 = 0.4, 0.3, 0.2, 0.1
    scores = {}
    for node in unvisited_nodes:
        all_distances = [distance_matrix[node][i] for i in unvisited_nodes if i != node]
        average_distance_to_unvisited = np.mean(all_distances)
        std_dev_distance_to_unvisited = np.std(all_distances)
        score = c1 * distance_matrix[current_node][node] - c2 * average_distance_to_unvisited + c3 * std_dev_distance_to_unvisited - c4 * distance_matrix[destination_node][node]
        scores[node] = score
    next_node = min(scores, key=scores.get)
    return next_node
[2024-04-08 13:05:19,389][root][INFO] - Iteration 0: Running Code 0
[2024-04-08 13:05:19,553][root][INFO] - Iteration 0: Code Run 0 execution error!
[2024-04-08 13:05:19,572][root][INFO] - Iteration 0, response_id 0: Objective value: inf
Error executing job with overrides: ['problem=tsp_constructive', 'algorithm=reevo']
Traceback (most recent call last):
  File "C:\Users\kjkj0\LLM-as-HH\main.py", line 52, in <module>
    main()
  File "C:\Users\kjkj0\LLM-as-HH\revo-venv-ziphu\Lib\site-packages\hydra\main.py", line 94, in decorated_main
    _run_hydra(
  File "C:\Users\kjkj0\LLM-as-HH\revo-venv-ziphu\Lib\site-packages\hydra\_internal\utils.py", line 394, in _run_hydra
    _run_app(
  File "C:\Users\kjkj0\LLM-as-HH\revo-venv-ziphu\Lib\site-packages\hydra\_internal\utils.py", line 457, in _run_app
    run_and_report(
  File "C:\Users\kjkj0\LLM-as-HH\revo-venv-ziphu\Lib\site-packages\hydra\_internal\utils.py", line 223, in run_and_report
    raise ex
  File "C:\Users\kjkj0\LLM-as-HH\revo-venv-ziphu\Lib\site-packages\hydra\_internal\utils.py", line 220, in run_and_report
    return func()
           ^^^^^^
  File "C:\Users\kjkj0\LLM-as-HH\revo-venv-ziphu\Lib\site-packages\hydra\_internal\utils.py", line 458, in <lambda>
    lambda: hydra.run(
            ^^^^^^^^^^
  File "C:\Users\kjkj0\LLM-as-HH\revo-venv-ziphu\Lib\site-packages\hydra\_internal\hydra.py", line 132, in run
    _ = ret.return_value
        ^^^^^^^^^^^^^^^^
  File "C:\Users\kjkj0\LLM-as-HH\revo-venv-ziphu\Lib\site-packages\hydra\core\utils.py", line 260, in return_value
    raise self._return_value
  File "C:\Users\kjkj0\LLM-as-HH\revo-venv-ziphu\Lib\site-packages\hydra\core\utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kjkj0\LLM-as-HH\main.py", line 31, in main
    reevo = ga(cfg, ROOT_DIR)
            ^^^^^^^^^^^^^^^^^
  File "C:\Users\kjkj0\LLM-as-HH\reevo.py", line 26, in __init__
    self.init_population()
  File "C:\Users\kjkj0\LLM-as-HH\reevo.py", line 98, in init_population
    raise RuntimeError(f"Seed function is invalid. Please check the stdout file in {os.getcwd()}.")
RuntimeError: Seed function is invalid. Please check the stdout file in C:\Users\kjkj0\LLM-as-HH\outputs\main\2024-04-08_13-05-18.
```

**Comment by henry-yeh** [comment]
Hi, thanks for your interest!
Could you please check out what's in the stdout file in C:\Users\kjkj0\LLM-as-HH\outputs\main\2024-04-08_13-05-18?

**Comment by henry-yeh** [comment]
Everything should be fine now. Thanks for your contribution!

**Comment by AHMED-salah00** [comment]
I've tried to run again, and the same error appears. I don't see what is the use of that change. Can you try to run it from your side? It already ran successfully with one of my colleagues, but we both don't know how!

**Comment by henry-yeh** [comment]
Can you provide the error message in the latest std file? The one in C:\Users\kjkj0\LLM-as-HH\outputs\main\xxx

**Comment by AHMED-salah00** [comment]
Yes, that worked fine now. Thanks for your feedback!

**Comment by henry-yeh** [comment]
Yes, you can achieve that by modifying the code below.

https://github.com/ai4co/LLM-as-HH/blob/ac8f3b39bab614bb970ebdb1ca2fcb36ad1a4a76/utils/utils.py#L9-L19

https://github.com/ai4co/LLM-as-HH/blob/ac8f3b39bab614bb970ebdb1ca2fcb36ad1a4a76/utils/utils.py#L87-L121
